# Generated by Django 4.2.4 on 2023-08-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infform',
            name='is_draft',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='jafform',
            name='is_draft',
            field=models.BooleanField(),
        ),
    ]
