# Generated by Django 4.2.4 on 2023-08-08 09:50

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctc_gross', models.TextField()),
                ('ctc_take_home', models.TextField()),
                ('ctc_bonus_perks', models.TextField()),
                ('bond_contract', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppt', models.BooleanField()),
                ('shortlist_from_resume', models.BooleanField()),
                ('written_test', models.BooleanField()),
                ('online_test', models.BooleanField()),
                ('technical_test', models.BooleanField()),
                ('aptitude_test', models.BooleanField()),
                ('psychometric_test', models.BooleanField()),
                ('group_discussion', models.BooleanField()),
                ('personal_interview', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SelectionProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eligibility_criteria', models.TextField()),
                ('allow_backlog_students', models.BooleanField()),
                ('test_duration', models.CharField(max_length=50)),
                ('likely_topics', models.TextField()),
                ('number_of_rounds', models.PositiveIntegerField()),
                ('group_discussion_duration', models.CharField(max_length=50)),
                ('number_of_offers', models.PositiveIntegerField()),
                ('preferred_period', models.CharField(max_length=50)),
                ('logistics_requirements', models.TextField()),
                ('interested_discipline', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(blank=True, default=dict), size=None)),
                ('test_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.testtype')),
            ],
        ),
        migrations.CreateModel(
            name='JAFForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=255)),
                ('organisation_postal_address', models.TextField()),
                ('organisation_website', models.URLField()),
                ('organisation_type_options', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('organisation_type_others', models.TextField()),
                ('industry_sector_options', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('industry_sector_others', models.TextField()),
                ('job_profile_designation', models.CharField(max_length=255)),
                ('job_profile_job_description', models.TextField()),
                ('job_profile_job_description_pdf', django.contrib.postgres.fields.ArrayField(base_field=models.FileField(upload_to='job_description_pdfs/'), size=None)),
                ('job_profile_place_of_posting', models.CharField(max_length=255)),
                ('contact_details_first_person_of_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_person_of_contact', to='api.contactdetails')),
                ('contact_details_head_hr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='head_hr', to='api.contactdetails')),
                ('contact_details_second_person_of_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_person_of_contact', to='api.contactdetails')),
                ('salary_details_b_tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b_tech', to='api.salarydetails')),
                ('salary_details_m_sc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_sc', to='api.salarydetails')),
                ('salary_details_m_tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_tech', to='api.salarydetails')),
                ('salary_details_phd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phd', to='api.salarydetails')),
                ('selection_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selection_process', to='api.selectionprocess')),
            ],
        ),
    ]
