# Generated by Django 4.2.4 on 2023-08-09 16:45

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_infform_is_draft_alter_jafform_is_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetails',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
