# Generated by Django 4.2.4 on 2023-08-09 05:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_infform_industry_sector_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infform',
            name='industry_sector_options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None),
        ),
        migrations.AlterField(
            model_name='jafform',
            name='industry_sector_options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None),
        ),
    ]
