# Generated by Django 4.2.4 on 2023-08-12 13:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_contactdetails_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interesteddiscipline',
            name='id',
        ),
        migrations.AlterField(
            model_name='infform',
            name='industry_sector_options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='infform',
            name='industry_sector_others',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='infform',
            name='job_profile_designation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='infform',
            name='job_profile_job_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='infform',
            name='job_profile_job_description_pdf',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(upload_to='job_description_pdfs/'), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='infform',
            name='job_profile_place_of_posting',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='infform',
            name='organisation_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='infform',
            name='organisation_postal_address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='infform',
            name='organisation_type_options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='infform',
            name='organisation_type_others',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='infform',
            name='organisation_website',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='interesteddiscipline',
            name='degree',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jafform',
            name='industry_sector_options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='jafform',
            name='industry_sector_others',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='jafform',
            name='job_profile_designation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jafform',
            name='job_profile_job_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='jafform',
            name='job_profile_job_description_pdf',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(upload_to='job_description_pdfs/'), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='jafform',
            name='job_profile_place_of_posting',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jafform',
            name='organisation_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jafform',
            name='organisation_postal_address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='jafform',
            name='organisation_type_options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='jafform',
            name='organisation_type_others',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='jafform',
            name='organisation_website',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='salarydetails',
            name='bond_contract',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='salarydetails',
            name='ctc_bonus_perks',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='salarydetails',
            name='ctc_gross',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='salarydetails',
            name='ctc_take_home',
            field=models.TextField(null=True),
        ),
    ]
