# Generated by Django 4.2.4 on 2023-08-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_interesteddiscipline_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectionprocess',
            name='interested_discipline',
            field=models.TextField(),
        ),
    ]
