# Generated by Django 4.2.4 on 2023-08-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_selectionprocess_interested_discipline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infform',
            name='job_profile_job_description_pdf',
            field=models.FileField(null=True, upload_to='job_description_pdfs/'),
        ),
        migrations.AlterField(
            model_name='jafform',
            name='job_profile_job_description_pdf',
            field=models.FileField(null=True, upload_to='job_description_pdfs/'),
        ),
    ]
