# Generated by Django 4.2.4 on 2023-08-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_infform_job_profile_job_description_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infform',
            name='versionTitle',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jafform',
            name='versionTitle',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
