# Generated by Django 4.2.4 on 2023-08-17 16:02

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_infform_submitted_by_jafform_submitted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infform',
            name='job_profile_job_description_pdf',
        ),
        migrations.RemoveField(
            model_name='jafform',
            name='job_profile_job_description_pdf',
        ),
        migrations.CreateModel(
            name='FileObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=api.models.fileSavePath)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='infform',
            name='job_profile_job_description_pdf',
            field=models.ManyToManyField(blank=True, null=True, to='api.fileobject'),
        ),
        migrations.AddField(
            model_name='jafform',
            name='job_profile_job_description_pdf',
            field=models.ManyToManyField(blank=True, null=True, to='api.fileobject'),
        ),
    ]
