# Generated by Django 4.2.4 on 2023-08-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_infform_job_profile_job_description_pdf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('shortcut', models.CharField(max_length=10)),
                ('degree', models.CharField(choices=[('BTech', 'BTech'), ('BTech with minor in', 'BTech with minor in'), ('Dual Degree', 'Dual Degree'), ('MTech', 'MTech'), ('MSc', 'MSc'), ('PhD', 'PhD')], max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='selectionprocess',
            name='interested_discipline',
            field=models.JSONField(),
        ),
    ]
