# Generated by Django 4.2.4 on 2023-08-19 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_userotp_user_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
    ]
