# Generated by Django 4.2.4 on 2023-08-20 03:49

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_user_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetails',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='phone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='infform',
            name='contact_details_first_person_of_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_person_of_contactINF', to='api.contactdetails'),
        ),
        migrations.AlterField(
            model_name='infform',
            name='contact_details_head_hr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='head_hrINF', to='api.contactdetails'),
        ),
        migrations.AlterField(
            model_name='infform',
            name='contact_details_second_person_of_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_person_of_contactINF', to='api.contactdetails'),
        ),
        migrations.AlterField(
            model_name='infform',
            name='industry_sector_options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='infform',
            name='industry_sector_others',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='infform',
            name='job_profile_designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='infform',
            name='job_profile_job_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='infform',
            name='job_profile_joint_master_thesis_program',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='infform',
            name='job_profile_place_of_posting',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='infform',
            name='job_profile_six_months_intern',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='infform',
            name='job_profile_two_months_intern',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='infform',
            name='organisation_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='infform',
            name='organisation_postal_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='infform',
            name='organisation_type_options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='infform',
            name='organisation_type_others',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='infform',
            name='organisation_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='infform',
            name='stipend_details_accodation_trip_fare',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='infform',
            name='stipend_details_bonus_perks_incentives',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='infform',
            name='stipend_details_bonus_service_contract',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='infform',
            name='stipend_details_stipend_amount',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='infform',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='infform',
            name='versionTitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jafform',
            name='contact_details_first_person_of_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_person_of_contactJAF', to='api.contactdetails'),
        ),
        migrations.AlterField(
            model_name='jafform',
            name='contact_details_head_hr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='head_hrJAF', to='api.contactdetails'),
        ),
        migrations.AlterField(
            model_name='jafform',
            name='contact_details_second_person_of_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_person_of_contactJAF', to='api.contactdetails'),
        ),
        migrations.AlterField(
            model_name='jafform',
            name='industry_sector_options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='jafform',
            name='industry_sector_others',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jafform',
            name='job_profile_designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jafform',
            name='job_profile_job_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jafform',
            name='job_profile_place_of_posting',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jafform',
            name='organisation_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jafform',
            name='organisation_postal_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jafform',
            name='organisation_type_options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='jafform',
            name='organisation_type_others',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jafform',
            name='organisation_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jafform',
            name='salary_details_b_tech',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b_tech', to='api.salarydetails'),
        ),
        migrations.AlterField(
            model_name='jafform',
            name='salary_details_m_sc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m_sc', to='api.salarydetails'),
        ),
        migrations.AlterField(
            model_name='jafform',
            name='salary_details_m_tech',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m_tech', to='api.salarydetails'),
        ),
        migrations.AlterField(
            model_name='jafform',
            name='salary_details_phd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phd', to='api.salarydetails'),
        ),
        migrations.AlterField(
            model_name='jafform',
            name='selection_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selection_processJAF', to='api.selectionprocess'),
        ),
        migrations.AlterField(
            model_name='jafform',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jafform',
            name='versionTitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='selectionprocess',
            name='allow_backlog_students',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='selectionprocess',
            name='eligibility_criteria',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='selectionprocess',
            name='group_discussion_duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='selectionprocess',
            name='interested_discipline',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='selectionprocess',
            name='likely_topics',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='selectionprocess',
            name='logistics_requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='selectionprocess',
            name='number_of_offers',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='selectionprocess',
            name='number_of_rounds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='selectionprocess',
            name='preferred_period',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='selectionprocess',
            name='test_duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='selectionprocess',
            name='test_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.testtype'),
        ),
        migrations.AlterField(
            model_name='testtype',
            name='aptitude_test',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='testtype',
            name='group_discussion',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='testtype',
            name='online_test',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='testtype',
            name='personal_interview',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='testtype',
            name='ppt',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='testtype',
            name='psychometric_test',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='testtype',
            name='shortlist_from_resume',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='testtype',
            name='technical_test',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='testtype',
            name='written_test',
            field=models.BooleanField(null=True),
        ),
    ]
